# Generated by Django 3.1.7 on 2021-04-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_addtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='ad_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.addtype'),
        ),
    ]
